### ISSUE TITLE
Visual Studio 2017 Support

### ISSUE THREAD

**Issue by RBBuff** [HedgehogDevelopment/Helix-FXCop-Rules#1]
I created a HelixRules.ruleset file with the below XML and put it along side the HedgehogDevelopment.FxCop.Helix.dll code analysis library.  This enabled Helix rules enforcement within VS 2017.  Hope this helps.

```<RuleSet Name="Hedgehog Helix Ruleset" Description="These rules focus on enforcing Helix architecture principles." ToolsVersion="12.0">
  <Rules AnalyzerId="Microsoft.Analyzers.ManagedCodeAnalysis" RuleNamespace="Microsoft.Rules.Managed">
    <Rule Id="ScHlx001" Action="Warning" />
    <Rule Id="ScHlx002" Action="Warning" />
    <Rule Id="ScHlx004" Action="Warning" />
    <Rule Id="ScHlx005" Action="Warning" />
    <Rule Id="ScHlx006" Action="Warning" />
  </Rules>
</RuleSet>

**Comment by coffee-lover16** [comment]
Here is described it supports VS 2015 only:

https://www.hhog.com/blog/sitecore-helix-fxcop-rules

Nothing changed and is it still work with VS 2015 only?

**Comment by cturano** [comment]
Hi Evgeniy,
   It works with VS 2017. you need to locate the VS2017 install folder, which is a bit more difficult to describe since MS changed the installer and the install location can vary from computer to computer.

Charlie

**Comment by coffee-lover16** [comment]
Hello Charlie,

Thanks for your reply! It really works if I put the assembly to the VS 2017 folder

**Comment by SaintSkeeta** [comment]
For VS 2019, The FxCop rules folder can be found here:-
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Static Analysis Tools\FxCop\Rules

Note, swap out 'Enterprise' for your edition of the IDE.
